// 
// Do not edit this file, it is automatically generated!
// To generate this file, "make design.h" in the rtl directory.
// 
#ifndef DESIGN_H
#define DESIGN_H

#timescale	1ps / 1ps
#define	INCLUDE_ZIPCPU
#define	WBUBUS_MASTER
#define	GPIO_ACCESS
#define	BKRAM_ACCESS
#define	BUSPIC_ACCESS
#define	BUSCONSOLE_ACCESS
#ifdef	INCLUDE_ZIPCPU
#else	// INCLUDE_ZIPCPU
#endif	// INCLUDE_ZIPCPU
#ifdef	GPIO_ACCESS
#else	// GPIO_ACCESS
#endif	// GPIO_ACCESS
#ifdef	WBUBUS_MASTER
#ifndef	BUSPIC_ACCESS
#endif
#else	// WBUBUS_MASTER
#endif	// WBUBUS_MASTER
#ifdef	INCLUDE_ZIPCPU
#else
#endif	// INCLUDE_ZIPCPU
#ifdef	WBUBUS_MASTER
#ifdef	INCLUDE_ZIPCPU
#define	BUS_DELAY_NEEDED
#endif
#endif
#ifdef	BUS_DELAY_NEEDED
#else
#endif
#ifdef	INCLUDE_ZIPCPU
#endif
#ifdef	BKRAM_ACCESS
#else	// BKRAM_ACCESS
#endif	// BKRAM_ACCESS
#ifdef	BUSPIC_ACCESS
#else	// BUSPIC_ACCESS
#endif	// BUSPIC_ACCESS
#ifdef	BUSCONSOLE_ACCESS
#else	// BUSCONSOLE_ACCESS
#endif	// BUSCONSOLE_ACCESS

#endif // DESIGN_H
